readme.md, src/git.js
This is the same as https://github.com/steveukx/git-js/pull/27. But working on a new branch just made it easier.
=> Added .show function.

src/git.js
* Split on whitespace instead of a fixed number of spaces
* Files that have been added to the staging area have different # spaces
=> Fix for git status

src/git.js
It didn't work (threw exceptions)
=> Fix errors in git-it (removeRemote and addRemote)

readme.md, src/git.js
This is obviously pretty basic. I'm currently using this in my own app like so:
```javascript
.revparse('HEAD', function(e, data){
```
Not sure if you'd like a test, just let me know.
=> Support revparse

readme.md
Hi there,
I tried to used command function but it always says object has no method command, so I had a look in the code and it seems like customBinary is the function to call
Great package btw,
Cheers
=> updates command to customBinary

src/git.js, test/testCommands.js
Quite a simple & straightforward addition, but very useful when using this library to serve git repositories. Let me know if there's any problems :)
=> Adds `update-server-info` command

readme.md, src/git.js, test/testCommands.js
https://git-scm.com/docs/git-check-ignore
=> Add checkIgnore for git check-ignore

src/git.js
First of all, thanks a lot for the library! I was looking for a simple git interface for a project and simple-git works really well. I was missing some status information from git, like the tracking branch and the distance from the remote in commits, which I'm using to conditionally show git status messages when there are changes, where changes can be any sort of change: modified files, unpushed commits, etc.
Let me know if you want it done in another way. I kind of just added to the sequence you were already using in `_parseStatus`.
This change updates the status function to include information about the
tracking branch, the current branch, number of commits ahead, and number
of commits behind. Now, the response for status will look as follows:
{ ahead: '1',
behind: '3',
current: …
=> Added branches and commit info to git status results

readme.md
but the actual function is .addConfig
=> set local config example incorrectly used .config

src/git.js
Here is the example output I used to test: https://regex101.com/r/xH0vJ1/1
=> Parsing improvements of Pull response

readme.md
Adding npm version badge into readme
=> Adding npm version badge

src/responses/BranchSummary.js, test/test-branch.js
Fix branches list for `git version 2.8.4 (Apple Git-73)`
=> Detached branch format more permissive

src/responses/PullSummary.js
=> Fixed deletion & insertion only pull summaries

test/integration/include/runner.js, test/integration/test-broken-chains.js
Additional tests to cover #136
=> Add broken-chain tests

src/git.js, test/unit/include/setup.js, test/unit/test-catfile.js, test/unit/test-commands.js
Adds the `binaryCatFile` option to return the buffer directly rather than first converting to a UTF8 String
Closes #156
=> Custom return format

typings/promise/index.d.ts
the following types has been added
- `checkout`
- `checkoutBranch`
- `checkoutLocalBranch`
- `mergeFromTo`
- `merge`
=> feat(typings): added more typings

src/responses/CommitSummary.js
=> Commit with extra author parameter

package.json, src/git.js
Run node with environment set DEBUG='simple-git' will show the git command actually execute.
Eg: 
```
➜  git-js git:(add_debug) DEBUG='simple-git' yarn test
yarn test v0.21.3
$ node node_modules/nodeunit/bin/nodeunit test/unit/test*.js
test-branch.js
simple-git [ 'branch', '-d', 'new-branch' ] +0ms
✔ branch - delete local branch with -d option
simple-git [ 'branch', '-D', 'new-branch' ] +10ms
✔ branch - delete local branch with -D option
simple-git [ 'branch', '--delete', 'new-branch' ] +5ms
✔ branch - delete local branch with --delete option
simple-git [ 'branch', '-d', 'new-branch' ] +2ms
✔ branch - delete local branch with #deleteLocalBranch
simple-git [ 'branch', '-d', 'new-branch' ] +2ms
✔ branch - delete local branch errors
✔ branch - detached branches
✔ branch - detached head at …
```
=> Add debug info

readme.md
I would have swapped var -> const but node v0.10.0 doesn't have full support for consts and that's what your `package.json` requires as the minimum version.
=> fix indentation, code highlighting and swap const -> var to support old node versions

src/responses/MergeSummary.js
added strict mode check as was getting Block-scoped declarations (let, const, function, class) not yet supported outside strict mode, at line 61
let mergeSummary = new MergeSummary();
=> added strict mode check in mergeSummary

src/git.js, test/unit/test-log.js
=> Reorder the `--max-count` option to appear before `--follow`

.editorconfig, typings/promise/index.d.ts
- added `.editorconfig` for more consistent formatting
=> types for methods `add` to `checkIsRepo`

typings/promise/index.d.ts
For some reason, my editor did not pick up these glaring error when I first finished
=> [fix] Fixing typing errors

src/responses/StatusSummary.js, test/unit/test-status.js, typings/response.d.ts
=> track staged files

src/responses/PullSummary.js
There was problem that when a file was deleted or added, not changed, it would not appear on the pull summary, because of the regex where it was expectating a space in the end of the line that was never there.
The error I reported here #150
=> Fixed only getting pull summary for changes on files

src/responses/DiffSummary.js
[issues 367 fix](https://github.com/steveukx/git-js/issues/367)
=> modify the Regex in binaryFileChange

src/git.js, src/responses/index.js
Switch lazy-loading to eager-loading of responses to allow for webpack bundling prior to the 2.x TS rewrite
Ref: #357
=> Eager loaded response handlers

test/integration/test-add.js
=> Adds integration test for adding files

.travis.yml, src/git.js, test/unit/include/setup.js
=> Support for node 10.x

src/responses/DiffSummary.js, test/unit/test-diff.js, test/unit/test-log.js, typings/response.d.ts
Read the `file(s) changed` section of the `diff` summary line to be used as `DiffSummary#changed`
Closes #385
=> DiffSummary 'changed'

.travis.yml, promise.js, src/responses/MergeSummary.js, test/integration/test-merge-integration.js
=> Include `git` property in promise wrapped exceptions

src/responses/StatusSummary.js, test/unit/test-status.js
Add unit tests covering the inclusion of renamed files in the StatusSummary response
=> StatusSummary shows renamed files

test/integration/test-remote.js
=> Add test for using `addRemote` and `remote(['set-url', ...])'`

readme.md, src/git.js, test/integration/test-check-is-repo.js, test/unit/test-check-is-repo.js, typings/simple-git.d.ts
- bare repo check in favor of #262
=> Bare repo check

readme.md
=> chore: fix readme typo

.github/workflows/ci.yml, test/integration/bad-initial-path.spec.ts, test/integration/timeout-plugin.spec.ts, test/unit/clean.spec.ts, test/unit/git.spec.ts, test/unit/plugin.error.spec.ts, test/unit/revert.spec.ts, typings/errors.d.ts
=> fix: Export `GitPluginError` from the main package.

examples/git-grep.md, packages/test-es-module-consumer/package.json, packages/test-javascript-consumer/package.json, packages/test-javascript-consumer/test-default.js, packages/test-typescript-consumer/package.json, readme.md, simple-git/CHANGELOG.md
- Absolute URLs for links in `.md` files
- Update import syntax, add test for named import style commons js
=> fix: Documentation update

docs/RELEASE-NOTES-V2.md, readme.md, simple-git/package.json, simple-git/src/git.js, simple-git/test/unit/commit.spec.ts, simple-git/test/unit/diff.spec.ts
- interfaces marked as deprecated through v2 should now result in a TaskConfigurationError
- update readme to remove references to deprecations
=> fix: implement v3 deprecations

.changeset/shy-carpets-agree.md, simple-git/readme.md, simple-git/src/git.js, simple-git/src/lib/types/index.ts, simple-git/src/lib/utils/simple-git-options.ts, simple-git/test/unit/raw.spec.ts
=> Trimmed raw responses

package.json, yarn.lock
=> Upgrade @changesets/changelog-github
