src/git.js, test/testCommands.js
I use `git version 2.5.0.windows.1`.
Accordingly [git documentation](https://git-scm.com/docs/git-status) status of the worktree can be empty (`Y` parametr) and when i make git.status i get wrong result.
=> Fix parse git status

src/git.js
I noticed that commands producing large stdout values return data with a ',' in the middle. It looks like you are performing a Buffer.concat() for stderr (line 726), but not stdout. This fix is working for me. I have not tested against most of the commands.
=> Concat stdOut buffers before then.call

src/git.js
quickfix for #46 copy&pasted boilerplate from git.log for option parsing.
=> Now git.show parses options like eg. git.log

src/git.js
Example:
git.log({n:2}, function(err, log){
console.log(err, log);
});
=> max count in log

src/git.js
```
user@ubuntu14043:~/Desktop/test$ git log
commit cf59ea355a8a78d9bade91d394e57616353326a4
Author: baz <foo@bar.xyz>
Date:   Mon Jan 4 18:30:04 2016 +0100
three   <--- this is the latest commit
commit 8f88715c0129a4edec7262af28328109190cfc3a
Author: baz <foo@bar.xyz>
Date:   Mon Jan 4 18:29:52 2016 +0100
two
commit e24826717fe9fc48e7375ab43102f9790e0cfb29
Author: baz <foo@bar.xyz>
Date:   Mon Jan 4 18:29:40 2016 +0100
one
user@ubuntu14043:~/Desktop/test$ node
> require('simple-git')().log(function(e,r) { console.log(r.latest); })
(...)
{ hash: '\'e24826717fe9fc48e7375ab43102f9790e0cfb29',
date: '2016-01-04 18:29:40 +0100',
message: 'one',
author_name: 'baz',
author_email: 'foo@bar.xyz\'' } <--- It returns the oldest commit.
```
Tested on git 2.6.4 on Windows and 1.9.1 on Linux Ubuntu. …
=> Fix wrong git.log.latest.

src/git.js, test/testCommands.js
git CLI allows us to commit message to have multiple lines with multiple flags -m  
example
```
git commit -m "some" -m "message"
```
=> add support multipleline message for commit

src/git.js, test/testCommands.js
I'm using this library with Heroku deployments and I don't have access to the git configuration. By default they don't have any user.name and user.email configured.
This PR aims to add support for addConfig function that will use the local instance to populate config options.
Usage:
```
_commitAndPushPost (resolve, reject) {
return simpleGit(root)
.outputHandler(function (command, stdout, stderr) {
stdout.pipe(process.stdout);
stderr.pipe(process.stderr);
})
.addConfig('user.name', USER_NAME)
.addConfig('user.email', USER_EMAIL)
...
}
```
=> Added support for add config keys.

src/StatusSummary.js, test/testCommands.js
The regex for parsing out the `current` in StatusSummary now handles periods in names.
=> Parsing improvements to StatusSummary

src/git.js
Adding functionality to send options into `.diffSummary` to use with `.diff`.
This allows for example to diff commit ids without them being the current HEAD.
=> Allowing .diffSummary to take options that are forwarded to .diff

readme.md
When using simple-git module, I was missing for an example for .listRemote(), so I added one. In progress, I noticed a few inconsistent indentations and missing semicolon and fixed those as well.
=> Fix some inconsistency in examples and added one for .listRemote()

src/StatusSummary.js, test/test-status.js
This adds the raw array of path / status letters to the result of git.status.
This allows to parse the types MM, DM, etc. that were currently skipped, without adding more arrays, and to differenciate if the modifications are on the index (like "M*(space)(space)*file.js") or working directory (like "*(space)*M*(space)*file.js")
=> Added raw files status in index / working dir in git.status

src/ListLogSummary.js, src/git.js, test/test-log.js
This adds an option "format" to git.log, which is an object that maps a field to a placeholder. This allows to use the other informations than only the hash/date/message/author's name and email
e.g.
```javascript
git.log({
format: {
'hash': '%H',
'message': '%s',
'refs': '%D',
'parents': '%P'
}
}, ...
```
=> Custom format option for git.log

.travis.yml, readme.md
This adds build status (npm test) badge on your readme. If you did not do it, you only have to github connect on [travis](https://travis-ci.org/) and enable it on [github](https://github.com/dwyl/learn-travis).
=> Add travis + badge

src/git.js, src/responses/ListLogSummary.js, test/unit/test-commands.js, test/unit/test-log.js
The fix allow the use of %b within the --pretty=format: when the description is written on more than one line.
A string is used in complement of \n to split commits.
=> Fix: handle multiline commit

src/git.js, test/unit/test-raw.js
I tried to run the `git.raw` command, but the following error occurred:
```
git: 'git' is not a git command. See 'git --help'.
```
It is obvious, that Git tries to execute something like `git git [args...]`.
According to the documentation:
> (module) Relies on git already having been installed on the system, and that it can be called using the command git.
So, there is no reason to prepend the arguments list with `'git'`, right?
`git.raw` as all the other methods use `_run(command, then, opt)` function to execute commands. None of them adds `'git'` as the first argument, except for `git.raw`.
We should do the opposite and remove the `'git'` if it's is present.
Or, we can remove the check for `'git'` as the first argument completely, as it was …
=> Fix `git.raw` command

src/git.js, test/integration/test-change-directory.js, test/unit/test-commands.js, test/unit/test-cwd.js
Adds validation to the `cwd` step to ensure the directory that will become the new working directory is a valid path before continuing.
Helps to diagnose issues noted in #159
=> Validate path when changing the working directory

src/git.js
Currently, when you have a folder and all files are untracked, it will list the folder instead of the files.
This changes it to list the files instead.
```txt
package.json (tracked)
/typings/simple-git/promise/index.d.ts (untracked)
/typings/simple-git/response.d.ts (untracked)
/typings/simple-git/ (all files are all untracked)
````
Current output `git status --porcelain -b`
```txt
M package.json
?? typings/simple-git/
```
Proposed output `git status --porcelain -b -u`
```txt
M package.json
?? typings/simple-git/promise/index.d.ts
?? typings/simple-git/response.d.ts
```
=> fix(status): list untracked files

src/git.js, test/unit/test-branch.js
This adds support for the git-branch `-D` and `--delete` options as described on issue #169 . 
I'm not sure I've written the unit tests correctly. Is there a better way to define the test once and then call it for each of the delete options? The tests themselves are the same but they depend on a fresh context for each option. I wasn't sure how to wrap the context in an iteration. I had something like this in mind:
```javascript
'delete local branch with options array': function (test) {
['-d', '-D', '--delete'].forEach(...)
}
```
Finally, what is the indentation used here? Is it three spaces?
=> Support all git-branch delete options`

src/git.js, test/unit/test-commands.js
Currently, when using diff-summary sometimes it trims file paths. This is a fix for it to always return full paths.
As you can see here without specifying the `--stat=XXX` value (the one above), it's trimming the file path.
And even worse, this is done inconsistently, sometimes it gives you full path if you only select one file.
NB: the reason to use 4096 is due to limit for linux (so hopefully it can never go wrong)
=> fix(diff summary): fix diff summary to always return full paths

typings/promise/index.d.ts
The promise typings currently omit `.silent()`, so Typescript fails to compile.
Adding the types for `.silent()` allowed my project to compile and life to move on 👍
=> Update typings with silent() method.

src/git.js, test/unit/include/setup.js
https://nodejs.org/api/child_process.html#child_process_event_exit
if underlying ssh connection is configured to `keepalive`, `stdout` will not close after git exit.
=> fix: change `close` to `exit`

package.json, src/git.js, test/unit/test-check-is-repo.js, test/unit/test-commands.js, test/unit/test-cwd.js, test/unit/test-log.js, test/unit/test-merge.js, test/unit/test-raw.js
Remove deprecated use of `.then` in exception handling of commands run through `.raw`
Use consistent importing of setup helpers in the tests
Use directory root for tests in the `npm test` command to allow for running tests on Windows
Closes #234
=> Modify tests for cleaner output and support nodeunit in Windows

.gitignore
it did not excluded files in subfolders, now it does
=> gitignore: corrected the exclusion pattern for typings folder

src/git.js, src/util/deferred.js, test/unit/include/setup.js, test/unit/test-commands.js, test/unit/test-git.js
Allow either the close or exit events on the child process to trigger the termination of that step of the tasks to be run.
In some cases (eg when keep-alive is used on the git connection), exit will emit but close will not (see 777ecfaa9a20ff5d843c43caf3242901497a6c3f).
In others, close will be emitted but not exit (see #252).
This change permits either to be used.
=> Respond to both close and exit events in the underlying child process

src/git.js
Adding the `/i` to the will also match `not a git repository` which is returned on some git versions.  Otherwise `checkIsRepo` will throw an error when the error return is not exactly  `Not a git repository`.
=> Case insensitive check for `Not a git repository`

typings/promise/index.d.ts
If you pass true to getRemotes it still returns an array even if there is only one remote. The return type for both function signatures should reflect that.
=> Fix TS typings for the getRemotes command

typings/promise/index.d.ts
Bizarrely, while fixing this VS Code suddenly wasn't having any issue with the non-prefixed `ReadableStream` type, so, I *think* this fixes #282? 🤷‍♂️
=> Adds the NodeJS namespace to ReadableStream. Fixes #282.

promise.d.ts
When building my TS project with simple-git 1.102.0 I got the following error:
```
error TS2371: A parameter initializer is only allowed in a function or constructor implementation.
245       init(bare = false): Promise<void>;
```
This PR fixes that.
=> fix: Remove default value from init() declaration

src/git.js, test/integration/include/runner.js, test/integration/test-concurrent-commands.js
Concurrently run commands can fail due to the close/exit events on the ChildProcess firing before data has been read into the stdOut/stdErr buffer.
When one fires without having received data, this change adds a timeout to allow for the next data event to finish processing before handling the child process closing.
(note: not guaranteed to always fix the errors).
=> Concurrent commands

src/git.js
When running Git workflows remotely using this repository, I was getting errors along the lines of: `Cannot find module './responses/BranchSummary'`.
Using absolute paths when requiring local modules solved this problem.
=> Use absolute paths for module dependencies

test/integration/test-check-is-repo.js
Adds tests to govern how `checkIsRepo` works against a real repo.
(ref: #345)
=> Add integration test for `checkIsRepo`

promise.js, test/integration/test-promise-on-bad-path.js
=> Add tests to cover the instantiation of the promise wrapped library with an invalid root folder.

src/git.js
On Windows, using `git-js` in a script stated with `forever` causes terminal window popups, similarly to this issue: https://github.com/foreversd/forever/issues/767. Setting `windowsHide` option to `true` fixes it.
=> add `windowsHide: true` option when spawning child process

readme.md, test/integration/test-log.js
Integration test for multi-line commit messages in a log summary
Closes #376
=> Add integration test for multi-line comments in a log summary

test/integration/test-log.js
Check the test: should read one line for each commit when using shortstat
Note, this is not a solution. At least not yet.
Any ideas on how to solve this without handling the --shortstat parameter separately?
Maybe put the seperator at the beginning of each line?
The shortstat is going inside the hash tag, is that also something we want?
=> Exposes issue #382

promise.d.ts
`{}` is the top-level type of all types, and as such [everything is valid](https://www.typescriptlang.org/play/#src=const%20fn%20%3D%20(p%3A%20%7B%7D)%20%3D%3E%20%7B%20%7D%3B%0A%0Afn(1)%3B%0Afn('')%3B%0Afn(%7B%7D)%3B%0Afn(()%20%3D%3E%20%7B%20%7D)%3B%0Afn(new%20Error())%3B%0Afn(undefined)%3B%0Afn(null)%3B%0Afn(Promise.resolve())%3B%0Afn(Symbol())%3B%0Afn(%5B%5D)%3B%0Afn()%3B).
I've also adjusted a couple of parameter type orders so that `Options` always comes first, for consistency.
I suspect that all `options: string[]` parameters can be typed as `options: Options`, but haven't used the library enough to be sure.
Let me know if that is the case, and I'll make that change too.
=> Replace `{}` type with `Options` type alias

src/git.js, test/unit/test-log.js
Force `--follow` to be appended to the set of supplied options in a `git.log`
Closes #389
=> Follow option in git.log

typings/response.d.ts
The property current of branch objects actually is of type boolean.
See here for the instantiation:
https://github.com/steveukx/git-js/blob/031ace112417034c0f1b60abaa399decdcafb5b0/src/responses/BranchSummary.js#L42
=> Correct BranchSummary declaration

src/responses/StatusSummary.js, test/unit/test-status.js
If two branches have added a new file with the same name and the content can't be automatically merged the file is not added in StatusSummary.conflicted.
Both sides have added the file conflict2.txt
```
$ git status --porcelain -b -u
AA conflict2.txt
```
=> If two branches have added the same file with conflicts. It should be added to StatusSummary.conflicted.

promise.d.ts, src/responses/MergeSummary.js, src/responses/StatusSummary.js, test/unit/test-merge.js, test/unit/test-status.js, typings/response.d.ts
Fixes #419 with the following changes:
* updated `git.status` should now report most types of merge conflicts, including modify/delete.
* updated `git.merge` to correctly parse the filename of modify/delete conflicts and also add a meta object containing information about where the file is deleted to distinguish between the file being deleted locally or remotely
Note that there are other conflicts that are not completely picked up by the parsers, they should report a conflict with a reason but not a file. The reason why I haven't implemented these is that there were quite a few different types of message structures and they all related to renames, which are hard to store in the existing conflicts data structure. I looked at https://github.com/git/git/blob/042ed3e048af08014487d19196984347e3 …
=> Parse and report modify delete conflicts

promise.d.ts
According to docs, `verbose` is an optional argument, yet calling the function without this argument causes a TypeScript error.
=> Fix `.getRemotes` type

CHANGELOG.md, src/git.js, test/unit/test-log.js
Adds assertion for using a leading options object in `git.log`
=> BugFix: await git.log

CHANGELOG.md, package.json, promise.d.ts, src/git-factory.js, src/index.js, src/lib/responses/BranchDeleteSummary.ts, src/lib/responses/BranchSummary.ts, src/lib/responses/CleanSummary.ts, src/lib/responses/ConfigList.ts, src/lib/responses/GetRemoteSummary.ts, src/lib/tasks/branch.ts, src/lib/tasks/clean.ts, src/lib/tasks/config.ts, src/lib/utils/util.ts, test/helpers.js, test/unit/git.spec.js, test/unit/include/setup.js, test/unit/utils.spec.js, tsconfig.json, typings/index.d.ts, typings/response.d.ts, typings/simple-git.d.ts, typings/types.d.ts
As noted in #473, the default export for `simple-git` would fail when imported without having `esModuleInterop` enabled in the `tsconfig.json`.
```typescript
import simpleGit, { SimpleGit } from 'simple-git';
expect(() => simpleGit()).not.toThrow();
```
=> Add support for use as an ES module with default export

CHANGELOG.md, src/lib/responses/PushSummary.ts, src/lib/utils/line-parser.ts, test/helpers.js, test/unit/push.spec.js, typings/response.d.ts
Include all `remote:` messages in the `PushResult` which would allow consumers of `simple-git` to apply their own custom parsing of the responses.
=> Feature: PushResult should contain all remote messages

CHANGELOG.md, src/lib/parsers/parse-merge.ts, src/lib/parsers/parse-pull.ts, src/lib/parsers/parse-remote-messages.ts, src/lib/parsers/parse-remote-objects.ts, src/lib/responses/ConfigList.ts, src/lib/responses/PullSummary.ts, src/lib/tasks/pull.ts, src/lib/utils/line-parser.ts, src/lib/utils/util.ts, test/unit/__fixtures__/index.js, test/unit/__fixtures__/remote-messages/constants.js, test/unit/__fixtures__/remote-messages/index.js, test/unit/__fixtures__/remote-messages/object-enumeration.js, test/unit/merge.spec.js, test/unit/pull.spec.js, test/unit/remote-messages.spec.js, test/unit/utils.spec.js, typings/response.d.ts
Already supported in response to a `push`, add support for `remote: ` messages in the response to a `git pull`
Closes #485
=> Feature: Pull remote messages

src/lib/tasks/log.ts, test/consumer/ts-default-from-root.spec.ts
`LogOptions` type should be intersection rather than union with `Options` type
Closes #506
=> BugFix: LogOptions type

.gitignore, src/git.js, src/lib/tasks/hash-object.ts, test/unit/hash-object.spec.ts, typings/simple-git.d.ts
Add git.hashObject. The `hash-object` command is used to compute object ID from a file.
=> Add git.hashObject

.github/workflows/ci.yml, CHANGELOG.md, package.json, src/lib/git-logger.ts, yarn.lock
Update `debug` dependency
Remove use of deprecated `debug().destroy()` - Closes #524
Renames the default source branch from `master` to `main`
=> Debug destroy

CHANGELOG.md, src/git.js, test/unit/log.spec.ts
Resolves an issue whereby using `git.log` with a callback (or awaiting the promise created from the now deprecated `simple-git/promise` import) would fail to return the response to the caller.
Closes #536
=> Bug fix for git.log

CHANGELOG.md, src/lib/responses/StatusSummary.ts, src/lib/tasks/status.ts, test/unit/__fixtures__/index.ts, test/unit/__fixtures__/responses/status.ts, test/unit/status.spec.ts
- Updates the `StatusResult` response to `git.status` to reference staged deletions/modifications in the `staged` array
- Adds support in status parsing for staged rename with unstaged modifications
- Return type in `statusTask` to be interface rather than concrete class
Closes #530
=> Git.status parsing

typings/simple-git.d.ts
mergeFromTo type is currently string, should be resp.MergeResult. (Executed on local, worked perfectly fine)
=> mergeFromTo type fixing

CHANGELOG.md, docs/LEGACY_NODE_VERSIONS.md, readme.md, src/lib/tasks/commit.ts, src/lib/tasks/log.ts, src/lib/utils/util.ts
Reinstate support for node.js v10 by switching to ES5 constructs object entries.
Closes #548
=> ES5 Support

CHANGELOG.md, promise.d.ts, src/lib/parsers/parse-commit.ts, src/lib/tasks/commit.ts, test/unit/__fixtures__/index.ts, test/unit/__fixtures__/responses/commit.ts, test/unit/commit.spec.ts, typings/response.d.ts, typings/simple-git.d.ts
- Adds support for detecting the `(root-commit)` token in response to a commit, representing a commit with no parent (ie: the initial commit).
- Renames `CommitSummary` to `CommitResult` (`CommitSummary` is now a deprecated alias of `CommitResult`)
Closes #520
=> Feature: handle initial commit

CHANGELOG.md, readme.md, src/git-factory.js, src/git.js, src/lib/plugins/command-config-prefixing-plugin.ts, src/lib/plugins/index.ts, src/lib/plugins/plugin-store.ts, src/lib/plugins/simple-git-plugin.ts, src/lib/runners/git-executor-chain.ts, src/lib/runners/git-executor.ts, src/lib/types/index.ts, src/lib/utils/simple-git-options.ts, src/lib/utils/util.ts, test/unit/plugins.spec.ts
Add `config: string[]` property to the `SimpleGitOptions` object used to configure the `simple-git` instance. When supplied, the strings are prefixed to all commands run by that instance as configuration options (ie: they are prefixed themselves with the `-c` flag).
Closes #562 - allows supplying custom proxies to the full set of API commands
Closes #559 - allows global commands
=> feat: custom / inline configuration

src/git.js, src/lib/runners/git-executor-chain.ts, src/lib/runners/git-executor.ts, src/lib/simple-git-api.ts, src/lib/types/index.ts, src/lib/utils/task-options.ts, src/lib/utils/util.ts, test/unit/add.spec.ts, typings/simple-git.d.ts
Creates a base interface `SimpleGitBase` (extended by the existing `SimpleGit`) to act as the container for all methods moved to the wholly TypeScript interface.
Refactor `SimpleGit['add']` to `SimpleGitBase` & add unit tests
=> feat: split the `git.add` into the ts `SimpleGitApi`

readme.md, src/git-factory.js, src/lib/plugins/plugin-store.ts, src/lib/plugins/progress-monitor-plugin.ts, src/lib/plugins/simple-git-plugin.ts, src/lib/runners/git-executor-chain.ts, src/lib/types/handlers.ts, src/lib/types/index.ts, src/lib/utils/util.ts, test/integration/progress-plugin.spec.ts, test/unit/__fixtures__/child-processes.ts, test/unit/__fixtures__/expectations.ts, test/unit/plugins.spec.ts, test/unit/utils.spec.ts
The `SimpleGitOptions` can now be used to supply a `progress` handler, called whenever progress data is received from one of the tasks. Setting the `progress` option will automatically add the `--progress` command to any `checkout` / `clone` or `pull` task when not already supplied in the `TaskOptions`.
For any task that ran with `--progress` as a command (ie: even `git.raw` so long as the `--progress` command was present), monitors the `stdErr` for progress data.
=> feat: Progress Handler

readme.md
fix: Update documentation for configuring `SimpleGit` - `options` should be a `Partial<SimpleGitOptions>` to allow for supplying just some of its properties.
closes #580
=> fix: Update configuration documentation

readme.md, src/lib/plugins/progress-monitor-plugin.ts, test/unit/plugins.spec.ts
fix: Progress plugin should request progress events for fetch as well as other common long running tasks.
=> Fix: Fetch Progress

test/unit/log.spec.ts, typings/response.d.ts
While use of the `ListLogSummary` type is deprecated in favour of the new `LogResult`, the alias type should also support the default generic `DefaultLogFields` to allow downstream consumers to upgrade to newer `2.x` versions without the need to specify a generic.
Closes #586
=> fix: ListLogSummary to support use without a generic

src/lib/parsers/parse-branch.ts, test/unit/__fixtures__/index.ts, test/unit/__fixtures__/responses/branch.ts, test/unit/branch.spec.ts
=> fix: parsing `git.branch` includes carriage returns

src/lib/runners/git-executor-chain.ts
Currently when an error happens the error message only includes `stdErr`. In some cases (at least `push`) `stdOut` would be very handy to also have in the message because it contains the actual reason why something failed.
It appeared in renovatebot/renovate#8354 that we are not able to push because of permission problems, but the error handler in our code cannot handle the error because the reason is only printed to `stdOut` by git and therefore not in the error message.
To prove what is logged by `git` I add a `console.log` statement to  https://github.com/steveukx/git-js/blob/main/src/lib/runners/git-executor-chain.ts#L242-L248 and this is what I see.
```
stdErr ---> Pushing to https://edcd21d09ed4ed5d6d24e7b05369459ea2ccb17f@github.com/reactjs/react-tabs.git
stdErr ---> POST …
```
=> Supply stdOut also to error handler

docs/DEBUG-LOGGING-GUIDE.md, package.json, readme.md, src/lib/git-logger.ts, src/lib/runners/scheduler.ts, test/unit/__mocks__/debug.ts, test/unit/git-executor.spec.ts, test/unit/logging.spec.ts, yarn.lock
Prior to this change, logging through the `debug` library had to be configured either by environment variable or by using the relevant apis in `debug` before requiring/importing `simple-git`.
Following this change, a script can call `debug.enable('simple-git:*`) at any point to ensure any `simple-git` instance created after that point logs accordingly.
=> feat: Support enabling / disabling `debug` logs programmatically.

examples/git-change-working-directory.md, readme.md, src/git.js, src/lib/runners/git-executor-chain.ts, src/lib/simple-git-api.ts, src/lib/tasks/change-working-directory.ts, src/lib/tasks/task.ts, src/lib/types/tasks.ts, test/__fixtures__/create-test-context.ts, test/integration/change-directory.spec.ts, typings/simple-git.d.ts
feat: `git.cwd` can now be configured to affect just the chain rather than root instance.
Adds a new interface for `git.cwd` to supply the `directory` as an object containing `{ path: string, root?: boolean }` where omitting the `root` property or setting it to `false` will change the working directory only for the chain, whereas setting `root` to `true` (or supplying `directory` as a string - for backward compatibility purposes) will change the working directory of the main instance.
=> feat: `git.cwd` can now be configured to affect just the chain rather than root instance.

readme.md
The URL was pointing to `git init` docs instead of `git merge`.
=> Fix URL of git command docs

readme.md, src/git.js, src/lib/simple-git-api.ts, test/unit/merge.spec.ts, typings/simple-git.d.ts
fix: updates the documentation for `mergeFromTo` to more closely represent its functionality (see #50 for the original requirement).
Move `mergeFromTo` to the TypeScript api and add tests to assert the enforcing of argument types.
=> mergeFromTo

readme.md, src/lib/git-factory.ts, src/lib/plugins/index.ts, src/lib/plugins/simple-git-plugin.ts, src/lib/plugins/spawn-options-plugin.ts, src/lib/runners/git-executor-chain.ts, src/lib/types/index.ts, src/lib/utils/util.ts, test/unit/__fixtures__/expectations.ts, test/unit/plugins.spec.ts
Currently the spawned `git` child processes all belong to the user/group of the parent process. This prevents using Simple Git on files owned by other uses without changing file ownership.
So, support a `spawnOptions` configuration option that passes through supported values (just `uid` and `gid`) to the `child_process.spawn` call that ultimately invokes `git`.
I made this work with a plugin modeled on the way custom config options get passed to the `git` command because that seemed like the most similar existing behavior. I am happy to switch this to the way environment variables work if that's more appropriate.
=> Allow setting system user and group IDs for spawned processes (proposed)

src/lib/parsers/parse-commit.ts, test/unit/__fixtures__/responses/commit.ts, test/unit/commit.spec.ts
fix: Commit parsing should cater for file names with square brackets
=> fix: Commit parsing should cater for file names with square brackets

test/unit/log.spec.ts, typings/response.d.ts
fix: use literal `true` and `false` in `DiffResultTextFile | DiffResultBinaryFile` to aid type assertions.
Closes #657
=> fix: literal true and false to aid type assertions

src/lib/task-callback.ts, src/lib/types/handlers.ts, test/integration/change-directory.spec.ts, test/unit/child-process.spec.ts, test/unit/cwd.spec.ts, test/unit/merge.spec.ts, test/unit/raw.spec.ts, test/unit/status.spec.ts
The TypeScript `Parameters` type doesn't permit creating a type that is the discriminating union of the argument tuples, meaning the `SimpleGitTaskCallback` was always typed as the error state `(err: E) => void`.
To resolve this, the `SimpleGitTaskCallback` is now typed with a single function type in the same way as the official `node` types: `(err: null | E, data: T) => void`.
=> feat: task callback types defined as single function type

readme.md, src/lib/responses/ConfigList.ts, src/lib/tasks/config.ts, test/unit/config.spec.ts, typings/response.d.ts, typings/simple-git.d.ts
`git.getConfig` add support for getting the current value of a git configuration setting based on its name.
```typescript
// read value from the combined settings git uses
expect(await git.getConfig('user.name')).toBe('My Name');
// read value from a specific scope
expect(await git.getConfig('user.name', 'local')).toBe('My Name In This Repo');
```
=> feat: `git.getConfig`

src/lib/plugins/progress-monitor-plugin.ts, test/unit/plugins.spec.ts
fix: support progress events in locales other than Western European character sets.
As identified in #579 - characters not recognised by the RegExp `/([a-zA-Z]+):/` cause the progress event handler to not recognise the message, change to the more flexible `/([\s\S]+):/`
=> fix: support progress events in locales other than Western European character sets.

docs/PLUGIN-COMPLETION-DETECTION.md, readme.md, src/lib/git-factory.ts, src/lib/plugins/completion-detection.plugin.ts, src/lib/plugins/index.ts, src/lib/plugins/simple-git-plugin.ts, src/lib/runners/git-executor-chain.ts, src/lib/types/index.ts, src/lib/utils/util.ts, test/integration/completion-plugin.spec.ts, test/unit/__fixtures__/child-processes.ts, test/unit/completion-detection-plugin.spec.ts
feat: `completion` plugin to allow configuring when `simple-git` determines the `git` tasks to be complete.
=> feat: `completion` plugin

test/unit/commit.spec.ts
To use `git.commit()` without any `-m` messages in the generated command, use an empty array for the `messages` argument:
```typescript
// an empty array is permitted in place of zero message string
const messages: string[] = [];
// or other selection of options as required for your purposes
const options: TaskOptions = { '--allow-empty': null };
git.commit(messages, options); 
```
Closes #694
=> fix: Add example for empty commit message in `git.commit()`

src/lib/responses/StatusSummary.ts, test/integration/status.spec.ts, test/unit/status.spec.ts, typings/response.d.ts
Include detached state in the `StatusResult` returned from `git.status()`.
Closes #693
=> fix: Include detached state in git.status

.gitignore, build/esm.js, package.json, src/esm.mjs, src/lib/api.ts, src/lib/git-factory.ts, src/lib/plugins/completion-detection.plugin.ts, yarn.lock
Following this change, it will be possible to import the default `simple-git` function along with the named exports in a single import - in the same way as it has been possible to for some time with TypeScript:
```javascript
// app.mjs
import simpleGit, { ResetMode } from 'simple-git';
await simpleGit().reset(ResetMode.HARD);
```
=> feat: Support loading with ES modules

simple-git/package.json
For backward compatibility - permit loading `simple-git/promise` with deprecation notice until mid-2022.
=> fix: Backward compatible imports

simple-git/src/lib/parsers/parse-pull.ts, simple-git/src/lib/responses/PullSummary.ts, simple-git/src/lib/tasks/pull.ts, simple-git/src/lib/utils/util.ts, simple-git/test/__fixtures__/setup-init.ts, simple-git/test/integration/pull-fails-ff.spec.ts, simple-git/test/unit/utils.spec.ts, simple-git/typings/response.d.ts, simple-git/typings/simple-git.d.ts
- parsers should treat `undefined` in either `stdout` or `stderr` the same as an empty string
=> fix: support parsing empty responses

simple-git/src/lib/responses/StatusSummary.ts, simple-git/test/unit/__fixtures__/responses/status.ts, simple-git/test/unit/status.spec.ts, simple-git/typings/response.d.ts
- When `git.status` is called with the `--ignored` flag, the `StatusResult` response will include an extra `ignored: string[]` property of ignored paths.
Closes #718
=> feat: optionally include ignored files in `StatusResult`

packages/babel-config/package.json, packages/test-es-module-consumer/package.json, packages/test-javascript-consumer/package.json, packages/test-typescript-consumer/package.json, simple-git/package.json
- Add repository metadata to `package.json` file(s)
Renovate bot cannot find the correct changelogs for the `simple-git` package.
I _think_ this is because the repository was recently changed to a monorepo, and npm no longer knows where the `package.json` file(s) are located.
Example of a PR with no changelogs: https://github.com/renovatebot/renovate/pull/13705
Relevant quote from npm 8 docs: [^npm-docs]
> If the `package.json` for your package is not in the root directory (for example if it is part of a monorepo), you can specify the directory in which it lives:
>
>
> ```json
> {
>   "repository": {
>     "type": "git",
>     "url": "https://github.com/facebook/react.git",
>     "directory": "packages/react-dom"
>   }
> }
> ```
I'm not sure if _all of these files_ need this change, maybe …
=> chore: add repository metadata to package.json

simple-git/src/lib/responses/StatusSummary.ts, simple-git/test/unit/status.spec.ts
This change enables calling the `isClean` method from `git.status` without the `StatusSummary` context (ie: when destructured):
```typescript
const { isClean } = await simpleGit().status();
expect( isClean() ).toBe( true );
```
=> feat: Support destructuring in `StatusSummary`.

.changeset/itchy-jobs-type.md, simple-git/src/lib/plugins/timout-plugin.ts
Clears the nodejs timeout upon stopping the listeners
Fixes #784
=> Clear timeout upon stop to avoid hanging the process

.changeset/hot-chairs-battle.md, simple-git/readme.md, simple-git/src/lib/args/log-format.ts, simple-git/src/lib/errors/git-error.ts, simple-git/src/lib/parsers/parse-branch-delete.ts, simple-git/src/lib/parsers/parse-diff-summary.ts, simple-git/src/lib/parsers/parse-fetch.ts, simple-git/src/lib/parsers/parse-list-log-summary.ts, simple-git/src/lib/parsers/parse-pull.ts, simple-git/src/lib/parsers/parse-push.ts, simple-git/src/lib/tasks/diff.ts, simple-git/src/lib/tasks/log.ts, simple-git/src/lib/tasks/stash-list.ts, simple-git/src/lib/tasks/task.ts, simple-git/src/lib/utils/task-parser.ts, simple-git/test/integration/diff.spec.ts, simple-git/test/integration/log.spec.ts, simple-git/test/unit/args.log-format.spec.ts, simple-git/test/unit/diff.spec.ts
The same parser is used to read per-file change summaries for `diff`, `log` and `stash` commands.
At present the format is assumed to always be `--stat=4096` so any use passing in alternative formats as custom options will find the result has either inaccurate information or misses files completely.
This change adds support for `--numstat` `--name-only` `--name-stat` and `--stat` in  `git.diffSummary`, `git.log` and `git.stashList`.
=> Support for log formats other than stat

.changeset/pink-gravy-boat.md, simple-git/src/lib/parsers/parse-branch.ts, simple-git/src/lib/responses/BranchSummary.ts, simple-git/test/unit/branch.spec.ts, simple-git/typings/response.d.ts
Branches that have been checked out as a [linked work tree](https://git-scm.com/docs/git-worktree) will now be included in the `BranchSummary` output, with a `linkedWorkTree` property set to `true` in the `BranchSummaryBranch`.
Closes #811
=> Add support for parsing linked worktree branches

docs/NON_ENGLISH_LOCALE.md
Add docs for how to run `git` commands with an English locale in order to ensure `simple-git` parsers parse.
=> English locale docs

.changeset/hip-ravens-smile.md, simple-git/src/lib/parsers/parse-fetch.ts, simple-git/test/integration/fetch.spec.ts, simple-git/typings/response.d.ts
Issue: https://github.com/steveukx/git-js/issues/823
Parses more of the git fetch response, notably updates + deletes.
This returns the to/from commit of each branch.
When `--prune` is passed, git will also return deleted branches.
=> feat(fetch) Add updated/deleted branches to fetch response.

.changeset/spotty-needles-leave.md, simple-git/readme.md, simple-git/src/lib/tasks/log.ts, simple-git/test/unit/log.spec.ts
=> Allow using just one of `from` and `to` in the `git.log` options.

docs/PLUGIN-UNSAFE-ACTIONS.md, simple-git/readme.md, simple-git/src/lib/git-factory.ts, simple-git/src/lib/plugins/block-unsafe-operations-plugin.ts, simple-git/src/lib/plugins/index.ts, simple-git/src/lib/types/index.ts, simple-git/test/integration/plugin.unsafe.spec.ts
Snyk recognised a potential vulnerability caused by passing unsanitised user data into commands that operate on a git remote (eg `clone`, `fetch`, `pull` and `push` etc) whereby an inline configuration argument could be used to enable the `ext::` protocol to switch out the remote for an arbitrary named binary run on the host machine.
While this highlights the need to sanitise user input in the application that consumes it before passing it through to any library, `simple-git` will now limit the use of these options unless the developer explicitly opts in to them with a new `allowUnsafeProtocolOverride` option.
=> Create the `unsafe` plugin to configure how `simple-git` treats known potentially unsafe operations.

.changeset/fair-cobras-arrive.md, docs/PLUGIN-UNSAFE-ACTIONS.md, simple-git/src/lib/plugins/block-unsafe-operations-plugin.ts, simple-git/test/unit/plugin.unsafe.spec.ts
Add `git push --exec` to the set of blocked operations without the use of an `allowUnsafePack` override.
/cc @stsewd
=> Block unsafe pack (push --exec)

simple-git/readme.md
This appears to be a typo? Anyway, super helpful package. Thanks for this. :)
=> Fix `git().pull` typo in readme

docs/PLUGIN-ERRORS.md
Just a simple correction in the docs. In the error handler, it is `exitCode`.
https://github.com/steveukx/git-js/blob/main/simple-git/src/lib/types/index.ts#L59
=> (chore): correction in simple git error handling example

.changeset/config.json, .changeset/smooth-roses-laugh.md, simple-git/readme.md, simple-git/src/lib/api.ts, simple-git/src/lib/args/pathspec.ts, simple-git/src/lib/git-factory.ts, simple-git/src/lib/plugins/suffix-paths.plugin.ts, simple-git/src/lib/utils/argument-filters.ts, simple-git/src/lib/utils/task-options.ts, simple-git/test/integration/add.spec.ts, simple-git/test/integration/grep.spec.ts, simple-git/test/unit/grep.spec.ts, simple-git/test/unit/plugin.pathspec.spec.ts, simple-git/typings/types.d.ts
Add the ability to append pathspec / file paths to the parameters passed through to git, automatically adding the `--` argument to separate file paths from the rest of the git command.
=> Pathspec / file lists supported in all TaskOptions

.changeset/sweet-steaks-draw.md, .github/workflows/ci.yml, simple-git/src/lib/tasks/log.ts, simple-git/test/unit/log.spec.ts
Switch to using a `pathspec` in `git.log` task to allow for the use of previously deleted files in the value of the `file` option.
Prior to this change users of `git.log` may have been explicitly appending `'--': null` to their `git.log` options argument, this is no longer required but should not cause any interruption if not removed from the calling code.
Closes #857
=> git.log should include a pathspec splitter automatically when using --follow

.changeset/six-cherries-grab.md, simple-git/src/lib/parsers/parse-diff-summary.ts
While investigating why running git log was taking so long for a repo (it's pretty large and there was some mass renaming). There was one commit (~4000 changed files) that was taking ~19s to parse the diff summary for and overall it would take ~40s. When running the equivalent native git command it only took ~8s.
Looking into it a bit more, I believe the main cause was that the regex is doing a lot of backtracking, especially for long filenames. So my fix was to just add `^` to make it match from the start of the line and avoid some backtracking. In ou
**Before:**
```js
> run = async () => {
const start = performance.now();
await simpleGit().log({ '--stat': 4906 });
console.log('Time', performance.now() - start);
}
> await run()
Time 40318.625875
```
**After:**
```js
> run = async () => { …
```
=> fix: stat diff summary performance

.changeset/brave-avocados-dress.md, simple-git/src/lib/parsers/parse-list-log-summary.ts, simple-git/test/unit/log.spec.ts
Resolve an issue when parsing the response to `git.log` that could leave part of the field separator in the preceding field.
The default splitter ` ò ` surrounds the character with spaces that were being trimmed through a needless use of `String#trim` in the parser.
Closes #985
=> Git log parser
